Feature/boardredux
SuhyeonP/trello pull request #32
Opened 2020-12-21 09:39 UTC by SuhyeonP

remove boardbackground
slice createDate is go to util folder
modify title
modify backcolor
etc

2020-12-21 11:11 UTC, dimsssss requested changes
기존에 있는 코드를 수정하는 코드는 feature에 안 넣는 게 좋을 것 같습니다. 

feature 브런치에서 작업을 할 때 기존에 있는 코드가 변경되지 않는다는 가정하에 코드를 작성하기 때문에 머지 후에 이유 없이 동작이 안될 수가 있어요.

그리고 코드 내용과 브런치 이름이 다르게 됩니다. 연결되어서 프론트와 백엔드 코드를 분리해서 풀리퀘 하는 것도 부탁드립니다.

2020-12-21 11:11 UTC, dimsssss commented on back/router/board.js
> +  }
try catch를 쓰시겠다면 실제 로직이 있는 service쪽(getBoard 메소드 안)에 넣는 게 낫지 않을까요

2020-12-21 11:11 UTC, dimsssss commented on back/model/board.js
>        },
value는 사용 하시나요?

2020-12-21 11:11 UTC, dimsssss commented on back/router/board.js
> +    res.status(200).json(result);
몰랐던 내용인데 덕분에 알게 됬습니다. :+1:

2020-12-22 05:12 UTC, SuhyeonP commented on back/model/board.js
>        },
네 이건 써용

2020-12-22 05:12 UTC, SuhyeonP commented on back/router/board.js
> +  }
아 그렇겟네용

2020-12-22 05:29 UTC, SuhyeonP commented on back/router/board.js
> +  }
서비스로 묶어 넣으니 오류가 나네요 ㅠ SSR때문에 그런거같은데 시간 여유되시면 확인 한번 부탁드릴게요 ㅠ

2020-12-22 06:17 UTC, dimsssss approved these changes

2020-12-22 06:25 UTC, merged